### ISSUE TITLE
Duplicate network requests with SSL Pinning 

### ISSUE THREAD

**Issue by DarkoDamjanovic** [Flipboard/FLEX#356] opened 2019-11-22 13:46 UTC
Hi,

I see a strange behaviour in the network monitor with enabled SSL Pinning. We observe duplicate network requests. The requests are not really done, as we can see on our backend logs. Just FLEX shows them with enabled SSP pinning. See here:

<img width=50% height=50% src=https://user-images.githubusercontent.com/11902775/69430769-9fe1ec80-0d36-11ea-905b-dde1ede4d2bc.png>

If we disable SSL pinning the effect is gone. Any hints are welcome. Thanks in advance.
Darko

**Comment by NSExceptional** [comment] 2019-11-22 19:46
I see you're using iOS 13. Does this happen when you test your app on iOS 12 as well?

**Comment by DarkoDamjanovic** [comment] 2019-11-25 09:18
No, it happens on both iOS 13 and iOS 12. 

Maybe you have any hints where to place breakpoints to understand where the second request is coming from?

**Comment by NSExceptional** [comment] 2019-11-25 21:02
Sure. Pretty much any of the `record*` methods in `FLEXNetworkRecorder.m`, or just `recordLoadingFinishedWithRequestID:responseBody:`

**Comment by NSExceptional** [comment] 2019-11-25 21:03
Closing as "can't reproduce." I will reopen this if you can upload an example project demonstrating the issue, or if you can point to something in FLEX causing this issue.

**Closed by NSExceptional** 2019-11-25 21:03 UTC

**Comment by DarkoDamjanovic** [comment] 2019-11-26 08:43
Thanks, I will investigate.

**Comment by phamquan** [comment] 2021-11-09 08:33
My project is using SSL Pinning and I see always double requests recorded as it is.

**Comment by NSExceptional** [comment] 2021-11-09 08:35
> I will reopen this if you can upload an example project demonstrating the issue, or if you can point to something in FLEX causing this issue.
