### ISSUE TITLE
Heap Objects and Classes empty

### ISSUE THREAD

**Issue by revolter** [Flipboard/FLEX#88] opened 2015-11-08 23:53 UTC
When trying to view Heap Objects and MyApp Classes instances, the results table views are empty, as you can see in the following screenshots:

[![Screenshot 1](http://i.imgur.com/Ra6AYIdm.jpg)](http://i.imgur.com/Ra6AYId.jpg) [![Screenshot 2](http://i.imgur.com/ZWe9NTkm.jpg)](http://i.imgur.com/ZWe9NTk.jpg)

[![Screenshot 3](http://i.imgur.com/D0TvbnQm.jpg)](http://i.imgur.com/D0TvbnQ.jpg) [![Screenshot 4](http://i.imgur.com/V7uYrDOm.jpg)](http://i.imgur.com/V7uYrDO.jpg)

When I first added this library, it worked, but it was often crashing, and suddenly stopped showing instances.

Even if I call `new` on a class, and the instance creates successfully, when I go back and select `Instances` it shows up empty.

How can I debug this problem? Does anyone have a clue about why is this happening?

I'm on my phone so I could add more info if needed later.

**Comment by ryanolsonk** [comment] 2015-11-10 17:09
Yea, unfortunately the heap objects feature has some inherent instability. The state of the application is constantly shifting underneath, so by the time you drill in, all the objects you saw in the first list may be gone. However, if you're never seeing any instances in the detail menus, that definitely sounds like a bug. I can't reproduce that myself, so maybe you can provide more details about your environment.

I'd also like to spend some time trying to reduce crashes in this area but it's not exactly a straightforward task. Simply retaining some of these objects or calling -description can cause crashes immediately or down the line. Also, any expectations of thread confinement will likely be violated through the presentation of this interface.

The code itself is not actually that complex if you want to poke around. I also think it's one of the more interesting areas of the tool. Check out `FLEXHeapEnumerator`, `FLEXLiveObjectsTableViewController`, and `FLEXInstancesTableViewController`.

**Comment by revolter** [comment] 2015-11-11 08:42
Well, I don't know what details would help. I guess (not sure) that it worked before [removing the files from the Release configuration](https://github.com/Flipboard/FLEX#excluding-flex-from-release-app-store-builds), but this shouldn't be a problem. And, it indeed crashed a couple of times, but now it doesn't crash at all.

It is indeed very interesting and useful, you can't imagine my reaction when I saw it. Thanks for the directions, I'll take a look when I have some time.

**Comment by ryanolsonk** [comment] 2015-11-12 16:42
Sorry, I could've been more clear. By details I meant simulator/device type, OS version, SDK version, etc.

**Comment by revolter** [comment] 2015-11-13 08:23
iPhone 6s and simulator, 9.1.1, I should've mentioned these in the first comment

**Comment by ryanolsonk** [comment] 2016-01-07 02:02
I think this is fixed now after the change in 94f06d5ff8ccb1cd4cdd4deeb07810d8a858ebd3. I'm unable to reproduce it at least. Please let me know if you continue to see it!

**Closed by ryanolsonk** 2016-01-07 02:02 UTC
Labels: bug

**Comment by revolter** [comment] 2016-01-07 08:49
Well, I figured it out. Dumb me commented out [this line](https://github.com/Flipboard/FLEX/blob/master/Classes/GlobalStateExplorers/FLEXInstancesTableViewController.m#L34) to stop the crashes, and forgot about it.
