### ISSUE TITLE
Unexpected crash for "Heap Objects" utility

### ISSUE THREAD

**Issue by xohozu** [Flipboard/FLEX#130] opened 2016-06-06 04:36 UTC
It must crash when did select "Heap Objects" each time.

![image](https://cloud.githubusercontent.com/assets/2561942/15812097/59fa7828-2be3-11e6-8d10-89fe912e07c0.png)

**Comment by sozorogami** [comment] 2016-06-06 16:40
This is a duplicate of #119

**Comment by ryanolsonk** [comment] 2016-07-29 23:26
Closing as duplicate.

**Closed by ryanolsonk** 2016-07-29 23:26 UTC
