### ISSUE TITLE
FLEX breaks custom WhatsApp's UIActionMenu 

### ISSUE THREAD

**Issue by Ram4096** [Flipboard/FLEX#373] opened 2020-01-22 19:32 UTC
This issue happens on every WhatsApp release. You can test it on 2.20.11.

1. Open a WhatsApp chat that contains a bubble message.
2. Tap and hold a message: you will see the custom UIActionMenu with its menu items. Tap anywhere to dismiss it.
3. Toggle FLEX to show the explorer bar.
4. Tap **select**, select anything, then **views**.
5. Tap the **info button**, go back and tap Done.
6. Close FLEX using the **Close** button.
7. Tap and hold a message again and no actions are shown.

**Comment by NSExceptional** [comment] 2020-01-22 20:05
Bleh. I'm sorry about this. I will see what I can do to fix it. I know exactly what's causing the issue: a fix for another issue within flex itself.

**Comment by Ram4096** [comment] 2020-01-23 00:43
So I guess you need to add a fix for the fix for the other issue within flex itself. 😜

**Comment by NSExceptional** [comment] 2020-01-23 02:25
Lol well the problem is FLEX's UIMenu actions weren't appearing because FLEX was higher than the `UITextEffectsWindow` in which they are placed. So I made the text window higher. I should probably just lower the flex window and see if that helps, lol

**Comment by NSExceptional** [comment] 2020-01-29 20:58
Hey @Ram4096, I finally got around to this. Can you test a fix for me? I can upload a deb

**Comment by Ram4096** [comment] 2020-01-29 21:00
@NSExceptional Yes for sure!

**Comment by NSExceptional** [comment] 2020-01-29 21:08
Here it is! Just remove the .zip extension, I had to add it so I could upload it here. It isn't actually compressed.

[libflex_4.0.0-beta.deb.zip](https://github.com/Flipboard/FLEX/files/4130722/libflex_4.0.0-beta.deb.zip)

**Comment by Ram4096** [comment] 2020-01-29 21:11
Unfortunately the issue is not fixed after installing this deb @NSExceptional

**Comment by NSExceptional** [comment] 2020-01-29 21:15
Hmm. I downloaded WhatsApp, I'm gonna dig into it myself now. Can you show me a screenshot if the message actions that disappear after opening FLEX?

**Comment by Ram4096** [comment] 2020-01-29 21:21
These message actions disappear if you follow exactly the procedure that I've previously described:
![683F3310-5DCB-4710-8C12-26F7FA21BBF7](https://user-images.githubusercontent.com/60160187/73398355-98fec980-42e5-11ea-8142-58154bce9e95.jpeg)

**Comment by NSExceptional** [comment] 2020-01-29 21:31
And you're on iOS 13 right?

**Comment by Ram4096** [comment] 2020-01-29 21:38
Yes. I've tested it on iOS 13.3. Using the version available on Cydia, I've tested it on iOS 12.4 too.

Note that the uploaded deb crashes on iOS 12.4, because "+[UIFont monospacedSystemFontOfSize:weight:]: unrecognized selector sento to class UIFont."

**Comment by NSExceptional** [comment] 2020-01-29 22:10
Weird, must be a typo in the SDK header, I'll update my code to accommodate it. Thanks for that.

Anyway, I've taken all of the `UITextEffectsWindow` related-code out and the problem still persists; I think this is just an issue with WhatsApp itself that I'm not able to easily work around.

I therefore will regretfully close this issue as a "won't fix," but I'll gladly accept a fix if someone manages to offer one up.

**Comment by Ram4096** [comment] 2020-01-29 22:59
@NSExceptional, do you use [[UIMenuController sharedMenuController] setMenuItems:] somewhere in your code to set UIMenuItem(s)?
If so, you should follow this:

1. Copy the old menuItems [UIMenuController sharedMenuController].menuItems.
2. Do your stuff with setMenuItems.
3. Before dismissing FLEX, restore the old menuItems.

The issue is finally fixed.
Apps that use sharedMenuController to set items might be afflicted  by the same issue.

**Comment by NSExceptional** [comment] 2020-01-29 23:01
Oh, I do! Is that what's causing it? Good idea. Reopening!

**Comment by Ram4096** [comment] 2020-01-29 23:04
Yes, it is exactly causing the issue. It seems like the entire WhatsApp menu items are replaced by "copyObjectAddress:", so WhatsApp doesn't show actions

**Comment by NSExceptional** [comment] 2020-01-29 23:36
Alright try this, now I back up and restore the menu items each time the flex window presents a modal screen

[libflex_4.0.0-beta.deb.zip](https://github.com/Flipboard/FLEX/files/4131399/libflex_4.0.0-beta.deb.zip)

**Comment by Ram4096** [comment] 2020-01-29 23:38
I confirm the issue is correctly fixed. Thank you 😁

**Comment by NSExceptional** [comment] 2020-01-29 23:39
Awesome! I'll go ahead and close this then, thanks again for your help and ideas!

**Closed by NSExceptional** 2020-01-29 23:39 UTC
Labels: bug

**Comment by Ram4096** [comment] 2020-01-29 23:50
Oops, I just found another way to reproduce the issue.
The issue is correctly fixed if I tap "Done", but if I invoke FLEX and I tap "Menu", on iOS 13 I can dismiss the "💪 FLEX" controller simply swiping down. If I swipe down and I don't press "Done", FLEX doesn't restore back UIMenuItems.

Oh, I've noticed that something might be different that the version hosted on Cydia. Did you edit something about window level or keyWindow? It seems like dismissing FLEX using the swipe down gesture, it doesn't restore the keyWindow probably and WhatsApp doesn't recognize its own window as keyWindow anymore.
Everything worked well on the version on Cydia.

**Comment by NSExceptional** [comment] 2020-01-30 00:22
WEW what a doozy this has been, haha. Alright, try this one. Nice catch, I would have never caught that on my own.

[libflex_4.0.0-beta.deb.zip](https://github.com/Flipboard/FLEX/files/4131539/libflex_4.0.0-beta.deb.zip)

If that's fixed, is there anything else?

**Comment by Ram4096** [comment] 2020-01-30 00:29
Yes! Everything is really fixed now! It's perfect, menu items are always restored and FLEX restores back the original keyWindow in any case: thank you very much!

**Comment by NSExceptional** [comment] 2020-01-30 00:44
Sure thing! And thank you!
