### ISSUE TITLE
FLEX doesn't log `NSURLSession` network requests (iOS 13, maybe before)

### ISSUE THREAD

**Issue by Nonepse** [Flipboard/FLEX#350] opened 2019-11-14 15:11 UTC
The Network History doesn't register requests made using `NSURLSession`. The ones made using `NSURLConnection` do show up.
This is an issue I've had for some time, using any version of FLEX (tried to rollback down to 2.1.0 and also tried the very last 3.1.0). So I suspect it's related iOS 13, but it could also have been happening before.

I understand `FLEXNetworkObserver` is working this way:
1. All delegate methods from `NSURLConnectionDataDelegate` and `NSURLSessionTaskDelegate` of all classes are swizzled
2. The swizzling blocks of `NSURLConnectionDataDelegate`'s `connection:willSendRequest:redirectResponse:` and its equivalent (is it though?) `NSURLSessionTaskDelegate`'s `URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:` are calling blocks which store the request (wrapped into a `FLEXNetworkTransaction` object) into `FLEXNetworkRecorder`'s `networkTransactionsForRequestIdentifiers` array
3. Once the request is finished (e.g. `URLSession:dataTask:didReceiveData:`), it is sent to `FLEXNetworkRecorder`
4. If `FLEXNetworkRecorder` finds that request in `networkTransactionsForRequestIdentifiers`, it will record it.

After investigation, I noticed that:
- `NSURLConnectionDataDelegate`'s `connection:willSendRequest:redirectResponse:` is called
- `NSURLSessionTaskDelegate`'s `URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:` **is never called**

Reading its documentation, Apple says
```
This method is called only for tasks in default and ephemeral sessions. Tasks in background sessions automatically follow redirects.
```
But my session is indeed a default one.

Now, I am not entirely sure those 2 methods are equivalent, and that I should expect it to be called when a request is sent.

However, I know that `NSURLSession`'s `resume` should always be called. And I see that this method too is swizzled, and its swizzling block is also performing the above-mentioned step 2 of `FLEXNetworkObserver`.

When checking how `resume` is swizzled, I see those comments:
```
// In iOS 7 resume lives in __NSCFLocalSessionTask
// In iOS 8 resume lives in NSURLSessionTask
// In iOS 9 resume lives in __NSCFURLSessionTask
```
Dat smelly smell.

After drilling through the iOS 13 ObjC runtime, I didn't really find any more interesting classes implementing that `resume` method.

<details>
  <summary>Unsatisfactory results</summary>
  
  ```javascript
  void DumpObjcMethods(Class clz) {
      unsigned int methodCount = 0;
      Method *methods = class_copyMethodList(clz, &methodCount);
      
      for (unsigned int i = 0; i < methodCount; i++) {
          Method method = methods[i];
          
          if (strcmp(sel_getName(method_getName(method)), "resume") == 0) {
              printf("\t'%s' has method named '%s' of encoding '%s'\n",
                     class_getName(clz),
                     sel_getName(method_getName(method)),
                     method_getTypeEncoding(method));
          }
      }
  
      free(methods);
  }
  ```
  
  ```
  [...]
  '__NSCFURLSessionConnection' has method named 'resume' of encoding 'v16@0:8'
  '__NSCFURLProxySessionConnection' has method named 'resume' of encoding 'v16@0:8'
  '__NSCFURLLocalSessionConnection' has method named 'resume' of encoding 'v16@0:8'
  '__NSCFURLLocalStreamTask' has method named 'resume' of encoding 'v16@0:8'
  '__NSCFURLSessionTask' has method named 'resume' of encoding 'v16@0:8'
  '__NSCFLocalSessionTask' has method named 'resume' of encoding 'v16@0:8'
  [...]
  ```
</details>

But after randomly playing with it and trying to force the use of `__NSCFLocalSessionTask` (which was the one for iOS 7), tadaa, the swizzling block is called, and network logs are back in Network History :tada:

So, did Apple move the implementation back to `__NSCFLocalSessionTask`? Since when? iOS 13.x? Before? Why has no-one noticed it? Why is `URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:` not called? Why am I asking so many questions?

I hope I was clear, thanks for any help 🙂

**Comment by NSExceptional** [comment] 2019-11-14 15:22
Hmmm, that is peculiar…

I'll investigate this when I have time, but in the meantime, PRs are welcome!

**Comment by Nonepse** [comment] 2019-11-14 15:25
btw, it seems highly related to https://github.com/Flipboard/FLEX/issues/341
I am happy to open a PR. Just wanted to share my results before opening one blindly.

**Comment by NSExceptional** [comment] 2019-11-17 06:03
Thanks man!

**Comment by Nosskirneh** [comment] 2020-03-07 07:32
I have a project where I need to replace network requests. On iOS 13, it stopped working with the reason being `__NSCFLocalSessionTask` is sometimes used instead of `NSURLSession`. Not all calls used the the first class, so I still needed the old hook for `NSURLSession`.

It worked perfectly fine on iOS 12.4. I haven't tested what happens below iOS 13.3 though.

**Comment by NSExceptional** [comment] 2020-03-07 17:56
If someone could make a small example project for me to test with, that would be awesome 😅

**Comment by Nosskirneh** [comment] 2020-03-08 10:31
I completely understand that. The code I'm targeting is not something I have written myself, so I'm not sure why those calls are using the `__NSCFLocalSessionTask` calls while my own added ones use the normal `NSURLSession`. It's a Xamarin app for all I know 🤷🏻‍♂️
I'll keep you posted if I find anything.

**Comment by NSExceptional** [comment] 2020-03-08 18:02
`__NSCFLocalSessionTask` and `NSURLSession` are in different class hierarchies; the former is a subclass if `NSURLSessionTask`.

**Comment by NSExceptional** [comment] 2020-03-13 19:36
@Nosskirneh @Nonepse Do either of you have a broken project you can send me that I can use to test? Or a simple reproducible case?

**Comment by NSExceptional** [comment] 2020-03-19 16:04
After some digging, I have discovered AFNetworking doing some bad swizzling is causing the issue. Looks like newer versions of AFNetworking don't have this problem, so if you're running into this issue, just update AFNetworking. I have also implemented a workaround that should work for apps you don't control using a bad version of AFNetworking, so you can still inspect traffic in those apps.

Fixed in the 4.0 branch. Also closing #341

**Closed by NSExceptional** 2020-03-19 16:04 UTC
Labels: awaiting response, bug, help wanted

**Comment by Nosskirneh** [comment] 2020-03-20 06:24
First off, thanks for looking into this and doing a greater good for the community!

Would weird code in AFNetworking result in different behavior specifically on iOS 13? I’m running the exact same .ipa as I did on iOS 12 and earlier versions.

I’m sorry I can’t provide an example project, the .ipa can’t be shared by legal reasons. I can try the new solution and see if it works better.

**Comment by NSExceptional** [comment] 2020-03-20 06:26
Possibly, yeah. AFNetworking isn't hard-coding class names like FLEX is, so the class it tries to target could definitely change between different iOS versions.

—
Tanner Bennett
