### ISSUE TITLE
App store problem

### ISSUE THREAD

**Issue by codeYMF** [Flipboard/FLEX#339] opened 2019-10-21 10:31 UTC
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/FLEX.framework/FLEX: _canPerformAction:forCell:sender:, _performAction:forCell:sender:, _tableView. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by NSExceptional** [comment] 2019-10-21 14:46
Duplicate of #298

**Closed by NSExceptional** 2019-10-21 14:46 UTC
